version: "3.8"

services:
  # =========================
  # EXISTING SETUP (UNCHANGED)
  # =========================

  nginx:
    image: neha874/django-nginx
    build:
      context: ./nginx
    container_name: "nginx_cont"
    ports:
      - "80:80"
    networks:
      - notes-app
    restart: always
    depends_on:
      - django

  db:
    container_name: "db_cont"
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - notes-app
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  django:
    image: neha874/django-notes-app
    build:
      context: .
    container_name: "django_cont"
    command: sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_PASSWORD: ${DB_PASSWORD}
      DEBUG: "False"
    restart: always
    depends_on:
      - db
    networks:
      - notes-app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s


  # =========================
  # NEW PROD-READY SETUP (ADDED)
  # =========================

  web:
    image: neha874/django-notes-app:${IMAGE_TAG}
    container_name: django_app
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    networks:
      - notes-app

  nginx_prod:
    image: neha874/django-nginx:${IMAGE_TAG}
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
    depends_on:
      - web
    networks:
      - notes-app


# =========================
# NETWORKS & VOLUMES
# =========================

networks:
  notes-app:

volumes:
  static_volume:
